distributionName: example-cdk-typescript

package:
  prePackage:
    commands:
      # If $GITHUB_SHA is available (build is running with GitHub actions)
      # set the deployment (distribution) id to $GITHUB_SHA.
      # Otherwise, create a moc test ID
      - |
          [[ -z $GITHUB_SHA ]] && GITHUB_SHA=$(date +%s)-test-id
          attini configure set-dist-id --id $GITHUB_SHA

      - npm install
      - npm test
      # Synthesizes the deployment plan, this template has to be environment agnostic
      - cdk synth --app "npx ts-node --prefer-ts-exts deployment-plan/deployment-plan.ts" > deployment-plan.yaml

initDeployConfig:
  template: deployment-plan.yaml
  stackName: ${environment}-${distributionName}-deployment-plan